### ISSUE TITLE
作品名から近隣の図書館の貸し出し情報を出力

### ISSUE THREAD

**Issue by yusukehaneda** [KozyDozy/rails_enpit#40]

**Comment by yusukehaneda** [comment]
作品名をキーに近隣の図書館の情報を出力します。ログインしてAPIキーを取得するアプリなのでNGですかね？

**Comment by kasai05** [comment]
APIキーを指定して取得する事自体は問題ないかと思います。
どこのAPIを利用するのか、API仕様書のページを連携頂けるますか？
